version: '3.8'
services:
  # redis-overcommit-on-host
  redis-overcommit:
    build: https://github.com/bkuhl/redis-overcommit-on-host.git
    restart: 'no'
    privileged: true
    volumes:
      - /proc/sys/vm:/mnt/vm
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
  web:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: yarn dev
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      DEBUG: background-tasks:*
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    depends_on:
    - redis-overcommit
    - cache
    links:
    - cache
volumes:
  cache:
    driver: local